### ISSUE TITLE
Investigate and improve bundle size

### ISSUE THREAD

**Issue by kleyu** [kleyu/currency-converter#4]
Right now, after building the app, the vendor chunk is bigger than 500kB. This is unacceptable for such a small app. 

Initial thoughts suggest that this might have to do something with icons tree-shaking not working, or the chart being heavy-loaded with JS.

**TODO**

- [ ] investigate using `rollup-bundle-analyzer`
- [ ] consider using `React.lazy` for loading the content of the second tab.
- [ ] see if moving to `preact` could shave-off some kBs.

**NOTE**: I don't plan to remove `react-query` as I'd like this project to be a testing ground for this lib.
