### ISSUE TITLE
Fix type warnings

### ISSUE THREAD

**Issue by kleyu** [kleyu/currency-converter#5]
After adding the `useLocalStorage` hook, its returned getter is not guaranteed to be a primitive type. It broke a lot of 
 type assumptions.

**TODO**

- [ ] Fix the new type warnings related to `useLocalStorage`
- [ ] Bring back `tsc` check in `npm run build`
- [ ] Ensure other types are not broken
